[build]
  publish = "."
  command = ""

[build.environment]
  NODE_VERSION = "18"
  NETLIFY_SKIP_YARN_INSTALL = "true"
  NETLIFY_SKIP_NPM_INSTALL = "true"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200